### PR TITLE
ElasticSource should clear the scroll

### LINKED ISSUE #3030: ElasticSource does not clear it's scroll
Was moving from the elastic4s-http-stream module to the elastic4s-pekko-stream module, i got a lot of errors on our internal test server. After some digging (because the actual root cause was is not clearly propagated to the stream error), i found out that the ElasticSource does not clear the scroll when finished, not on the elastic4s-pekko-stream nor on the elastic4s-akka-stream.

### PR DESCRIPTION
**Pull request by brunoballekens**
fixes #3030 

If you have suggestion for a test, please let me know.
If also changed the `asException` on ElasticError to include, if present and no causedBy is there, the first root cause

### CODE REVIEW

**Review by Philippus — APPROVED** [review]
LGTM

**Comment by brunoballekens** [comment]
Thx. Any timeline when this could be merged and a release be made ?

**Comment by Philippus** [comment]
You can try release 8.12.0-RC3, under a new organization name. So something like:
```libraryDependencies += "nl.gn0s1s" %% "elastic4s" % "8.12.0-RC3"```

**Comment by brunoballekens** [comment]
Thx

**Pull request merged**
